# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8dc8add10f8b6094bccbefb4e5cfd0597b8b339da045a16cea63ecf5cd48144521ed35def2ec2d6eb4c851615fc4cdd71eb92b6d15f680fb383c77b0d2dbc7fc

test:
  secret_key_base: e5f1d75f6cbebb7c8b4de9073a2b606fd0b94c6c79f8ab9ce8d44c63e15432306d244d8c4519837d02f9c117dec2492823ad7680f2c054b5d78d0521b1eaefff

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
